version: "3.3"

services:
  anvil:
    container_name: masters-anvil
    build:
      context: ./anvil
    ports:
      - "8545:8545"
  ipfs:
    container_name: masters-ipfs
    image: ipfs/kubo:v0.19.1
    volumes:
      - ./ipfs/container-init.d/001-profile.sh:/container-init.d/001-profile.sh
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
