version: "3.3"

services:
  anvil:
    container_name: masters-anvil
    build: ./anvil
    ports:
      - "8545:8545"
  # todo: make sure that docker-cache is used on CI env.
  blockchain:
    container_name: start-the-world
    network_mode: host
    build: ./organisation
    environment:
      - RUST_LOG=info
    command:
      - start-the-world
    depends_on:
      - anvil