version: "3.3"

services:
  anvil:
    container_name: masters-anvil
    build: ./anvil
    ports:
      - "8545:8545"
  blockchain:
    container_name: masters-blockchain
    network_mode: host
    build: ./blockchain
    depends_on:
      - anvil
