name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Master's thesis Poc
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      RUST_LOG: INFO
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install latest stable Rust
        uses: dtolnay/rust-toolchain@stable

      - name: rust version
        run: rustc --version

      - name: install foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: forge version
        run: forge --version

      - name: rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: organisation

      - name: cargo check
        run: >
          cargo check
          --manifest-path=organisation/Cargo.toml

      - name: cargo test
        run: >
          cargo test
          --manifest-path=organisation/Cargo.toml

      - name: forge tests -vvvvv
        run: >
          forge test -vvv
          --root=blockchain

      - name: run local anvil node and deploy smart contract
        run: >
          docker-compose up -d --build && 
          docker wait masters-blockchain &&
          docker logs masters-anvil &&
          docker logs masters-blockchain

      - name: curl
        run: curl localhost:8545 || echo "pinging localhost 8545"

      - name: integration tests
        run: cargo test --manifest-path=organisation/Cargo.toml -- --ignored --nocapture

      - name: tear down local anvil node
        run: docker-compose down
