name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Master's thesis Poc
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install latest stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Print Rust version
        run: rustc --version

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: organisation

      - name: Print Forge version
        run: forge --version

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: >
            --manifest-path=organisation/Cargo.toml

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: >
            --manifest-path=organisation/Cargo.toml

      - name: Run forge tests
        run: >
          forge test -vvv
          --root=blockchain
