name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Master's thesis Poc
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      RUST_LOG: INFO
      RUST_BACKTRACE: FULL
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build rust image
        uses: docker/build-push-action@v3
        with:
          context: ./organisation
          cache-from: type=registry,ref=petroniuss/masters-organisation:buildcache
          cache-to: type=registry,ref=petroniuss/masters-organisation:buildcache,mode=max
          tags: petroniuss/masters-organisation:latest
          push: true

      - name: Build blockchain image
        uses: docker/build-push-action@v3
        with:
          context: ./blockchain
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: petroniuss/masters-blockchain:latest
          push: false

      - name: Build anvil image
        uses: docker/build-push-action@v3
        with:
          context: ./anvil
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: petroniuss/masters-anvil:latest
          push: true

      - name: run local anvil node
        run: >
          docker-compose up -d && 
          docker logs masters-anvil

      # todo: run coordinator with a couple of peers.

      - name: tear down local anvil node
        run: docker-compose down
