name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Master's thesis Poc
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: install latest stable rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: rust version
        run: rustc --version

      - name: install foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: organisation

      - name: forge version
        run: forge --version

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: >
            --manifest-path=organisation/Cargo.toml

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: >
            --manifest-path=organisation/Cargo.toml

      - name: forge tests
        run: >
          forge test -vvv
          --root=blockchain

      - name: run local anvil node and deploy smart contract
        run: docker-compose up -d --build

      - name: integration tests
        run: export RUST_LOG=INFO && cargo test --manifest-path=organisation/Cargo.toml -- --ignored --nocapture

      - name: tear down local anvil node
        run: docker-compose down
