name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - ci-dockerized

jobs:
  check:
    name: Master's thesis Poc
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      RUST_LOG: INFO
      RUST_BACKTRACE: FULL
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build rust image
        uses: docker/build-push-action@v3
        working-directory: ./organisation
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: masters/organisation:latest
          push: false

      - name: run local anvil node and deploy smart contract
        run: >
          docker-compose up -d --build && 
          docker wait start-the-world &&
          docker logs start-the-world &&
          docker logs masters-anvil

      - name: cargo run register-peer-set
        working-directory: ./organisation
        run: >
          docker run masters/organisation:latest
          register-peer-set

      - name: curl
        run: curl localhost:8545 || echo "pinging localhost 8545"

      - name: tear down local anvil node
        run: docker-compose down
